### ISSUE TITLE
Select and add testing tool 

### ISSUE THREAD

**Issue by geemanjs** [lennym/govuk-react-components#7]
- [x] Select tool (I'd suggest Jest with Enzyme) 
- [x] Add packages 
- [x] Implement basic tests for current components
- [x] Add npm scripts for testing

**Comment by lennym** [comment]
~I'm a mocha fan myself, but happy to allow the honour of choosing a tool to go to whoever PRs tests first.~

Actually, jest looks pretty good for react. Let's do it.

**Comment by geemanjs** [comment]
Ok, I'll pick this up :D

**Comment by geemanjs** [comment]
We can also add Mocha later if we feel the need to:
https://github.com/airbnb/enzyme/blob/master/docs/guides/mocha.md

**Comment by lennym** [comment]
One comment I would add is to make sure that whatever test solution gets selected tests the exact code that gets published (i.e. the output of `npm run prepublish`) and doesn't perform any separate compilation steps (or if it does - i.e. wepback for browser execution) uses the compiled code as an input rather than compiling from src.
